### ISSUE TITLE
[WEBSITE] Barra lateral de contenido

### ISSUE THREAD

**Issue by SergioRibera** [RustLangES/rustmap#2]
Asi como en [roadmap.sh](https://roadmap.sh) se deberia abrir una barra lateral con el contenido markdown que corresponde al nodo seleccionado

![image](https://github.com/RustLangES/rustmap/assets/56278796/230f9367-222b-4e19-807e-0910460674f9)

Esta tarea consta de 3 etapas:
- [x] El componente de sidebar ( #11 )
- [x] Renderizacion del contenido Markdown ( #11 )
- [x] Permitir guardar el progreso localmente ( #11 )
  - > Por progreso se entiende el estado personal del contenido que puede ser `Por Leer, Leyendo, Completado y Saltar`
- [x] La barra lateral en modo Post (contenido extenso solo para lectura), mas detalles en el issue #5 ( #11 )
